name: beautynest_beautician
description: BeautyNest - Ladies Doorstep Salon Partner / Beautician Mobile App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  google_fonts: ^6.1.0
  intl: ^0.19.0
  cached_network_image: ^3.3.1
  http: ^1.2.0
  socket_io_client: ^2.0.3+1
  fl_chart: ^0.66.2
  geolocator: ^11.0.0
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
