export interface AdminBooking {
  id: string;
  bookingNumber: string;
  customerName: string;
  customerPhone: string;
  beauticianName: string;
  serviceName: string;
  timeSlot: string;
  amount: number;
  status: 'Confirmed' | 'On the Way' | 'In Progress' | 'Completed' | 'Cancelled';
  area: string;
  date: string;
}

export interface AdminBeautician {
  id: string;
  name: string;
  phone: string;
  email?: string;
  area: string;
  avatarUrl?: string;
  skills: string[];
  experienceYears: number;
  rating: number;
  totalJobs: number;
  isOnline: boolean;
  kycStatus: 'APPROVED' | 'PENDING' | 'REJECTED';
  earningsToday: number;
  aadhaarNumber?: string;
  upiId?: string;
}

export interface AdminCustomer {
  id: string;
  name: string;
  phone: string;
  area: string;
  totalBookings: number;
  totalSpent: number;
  lastBooking: string;
}

export const VARANASI_AREAS = [
  'Sigra',
  'Lanka (BHU)',
  'Assi Ghat',
  'Godowlia',
  'Dashashwamedh',
  'Bhelupur',
  'Varanasi Cantt',
  'Shivpur',
  'Mahmoorganj',
  'Orderly Bazar',
  'Pandeypur',
  'Sarnath',
  'Durgakund',
  'Luxa',
  'Rathyatra',
  'Maldahiya',
  'Chowk',
  'Nadesar',
  'Paharia',
  'Ramnagar',
] as const;

export const DASHBOARD_STATS = {
  todayRevenue: '₹1,48,560',
  totalBookings: 312,
  activeCustomers: 240,
  onlineBeauticians: 18,
};

export const CHART_DATA = [
  { time: '6 AM', bookings: 14, revenue: 11200 },
  { time: '9 AM', bookings: 52, revenue: 42800 },
  { time: '12 PM', bookings: 110, revenue: 89600 },
  { time: '3 PM', bookings: 165, revenue: 118400 },
  { time: '6 PM', bookings: 250, revenue: 139900 },
  { time: '9 PM', bookings: 312, revenue: 148560 },
];

export const RECENT_BOOKINGS: AdminBooking[] = [
  {
    id: 'b1',
    bookingNumber: 'BK-6887',
    customerName: 'Ritu Singh',
    customerPhone: '+91 98390 44551',
    beauticianName: 'Sunita Sharma',
    serviceName: 'Korean Glass Skin Hydra Ritual',
    timeSlot: '11:30 AM',
    amount: 899,
    status: 'Confirmed',
    area: 'Sigra, Varanasi',
    date: 'Today',
  },
  {
    id: 'b2',
    bookingNumber: 'BK-6888',
    customerName: 'Neha Verma',
    customerPhone: '+91 98390 44552',
    beauticianName: 'Pooja Maurya',
    serviceName: 'Full Body Waxing + D-Tan',
    timeSlot: '12:00 PM',
    amount: 1299,
    status: 'On the Way',
    area: 'Lanka (BHU), Varanasi',
    date: 'Today',
  },
  {
    id: 'b3',
    bookingNumber: 'BK-6889',
    customerName: 'Pooja Tandon',
    customerPhone: '+91 98390 44553',
    beauticianName: 'Neha Pandey',
    serviceName: 'Royal Kashi HD Bridal Makeup',
    timeSlot: '01:30 PM',
    amount: 4999,
    status: 'Completed',
    area: 'Godowlia, Varanasi',
    date: 'Today',
  },
  {
    id: 'b4',
    bookingNumber: 'BK-6890',
    customerName: 'Kavita Mishra',
    customerPhone: '+91 98390 44554',
    beauticianName: 'Rekha Vishwakarma',
    serviceName: 'L’Oreal Mythic Oil Hair Spa',
    timeSlot: '02:00 PM',
    amount: 789,
    status: 'Confirmed',
    area: 'Bhelupur, Varanasi',
    date: 'Today',
  },
  {
    id: 'b5',
    bookingNumber: 'BK-6891',
    customerName: 'Sneha Srivastava',
    customerPhone: '+91 98390 44555',
    beauticianName: 'Anjali Gupta',
    serviceName: 'Aromatherapy Relaxing Massage',
    timeSlot: '03:30 PM',
    amount: 1199,
    status: 'In Progress',
    area: 'Assi Ghat, Varanasi',
    date: 'Today',
  },
  {
    id: 'b6',
    bookingNumber: 'BK-6892',
    customerName: 'Divya Pandey',
    customerPhone: '+91 98390 44556',
    beauticianName: 'Kavita Mishra',
    serviceName: 'O3+ Whitening & Brightening Facial',
    timeSlot: '04:30 PM',
    amount: 1499,
    status: 'Confirmed',
    area: 'Mahmoorganj, Varanasi',
    date: 'Today',
  },
  // Tomorrow's Bookings
  {
    id: 'b7',
    bookingNumber: 'BK-6893',
    customerName: 'Swati Singh',
    customerPhone: '+91 98390 44557',
    beauticianName: 'Sunita Sharma',
    serviceName: 'Bridal Pre-Wedding Radiance Cleanup',
    timeSlot: '10:00 AM',
    amount: 1699,
    status: 'Confirmed',
    area: 'Lanka (BHU), Varanasi',
    date: 'Tomorrow',
  },
  {
    id: 'b8',
    bookingNumber: 'BK-6894',
    customerName: 'Aanchal Agrawal',
    customerPhone: '+91 98390 44558',
    beauticianName: 'Pooja Maurya',
    serviceName: 'HD Engagement Party Glam Makeup',
    timeSlot: '01:00 PM',
    amount: 3499,
    status: 'Confirmed',
    area: 'Sigra, Varanasi',
    date: 'Tomorrow',
  },
  {
    id: 'b9',
    bookingNumber: 'BK-6895',
    customerName: 'Rashmi Patel',
    customerPhone: '+91 98390 44559',
    beauticianName: 'Neha Pandey',
    serviceName: 'Rica Brazilian Chocolate Waxing + Manicure',
    timeSlot: '03:30 PM',
    amount: 1299,
    status: 'Confirmed',
    area: 'Varanasi Cantt, Varanasi',
    date: 'Tomorrow',
  },
  {
    id: 'b10',
    bookingNumber: 'BK-6896',
    customerName: 'Shikha Tiwari',
    customerPhone: '+91 98390 44560',
    beauticianName: 'Rekha Vishwakarma',
    serviceName: 'Kashi Ayurvedic Hair Rejuvenation Spa',
    timeSlot: '05:00 PM',
    amount: 999,
    status: 'Confirmed',
    area: 'Durgakund, Varanasi',
    date: 'Tomorrow',
  },
  // Day 3 Bookings (19 Sep 2026)
  {
    id: 'b11',
    bookingNumber: 'BK-6897',
    customerName: 'Meera Gupta',
    customerPhone: '+91 98390 44561',
    beauticianName: 'Poonam Tiwari',
    serviceName: 'Full Body Polishing & Jasmine Herbal Spa',
    timeSlot: '11:00 AM',
    amount: 2499,
    status: 'Confirmed',
    area: 'Shivpur, Varanasi',
    date: '19 Sep 2026',
  },
  {
    id: 'b12',
    bookingNumber: 'BK-6898',
    customerName: 'Kajal Yadav',
    customerPhone: '+91 98390 44562',
    beauticianName: 'Sunita Sharma',
    serviceName: 'Diamond Glow Cleanup + Detan',
    timeSlot: '02:30 PM',
    amount: 1199,
    status: 'Confirmed',
    area: 'Assi Ghat, Varanasi',
    date: '19 Sep 2026',
  },
  {
    id: 'b13',
    bookingNumber: 'BK-6899',
    customerName: 'Geeta Bhatt',
    customerPhone: '+91 98390 44563',
    beauticianName: 'Kavita Mishra',
    serviceName: 'Royal Kashi HD Bridal Makeup',
    timeSlot: '04:30 PM',
    amount: 4500,
    status: 'Confirmed',
    area: 'Pandeypur, Varanasi',
    date: '19 Sep 2026',
  },
  // Day 4 Bookings (20 Sep 2026)
  {
    id: 'b14',
    bookingNumber: 'BK-6900',
    customerName: 'Suman Upadhyay',
    customerPhone: '+91 98390 44564',
    beauticianName: 'Anjali Gupta',
    serviceName: 'Deep Tissue Aromatherapy Massage',
    timeSlot: '12:00 PM',
    amount: 1599,
    status: 'Confirmed',
    area: 'Rathyatra, Varanasi',
    date: '20 Sep 2026',
  },
  {
    id: 'b15',
    bookingNumber: 'BK-6901',
    customerName: 'Vandana Rai',
    customerPhone: '+91 98390 44565',
    beauticianName: 'Pooja Maurya',
    serviceName: 'Pre-Bridal Ubtan Glow + Waxing',
    timeSlot: '03:00 PM',
    amount: 2199,
    status: 'Confirmed',
    area: 'Sarnath, Varanasi',
    date: '20 Sep 2026',
  },
];

// 20 Realistic Beauticians across Varanasi with photos, ratings, areas, and KYC
export const BEAUTICIANS_LIST: AdminBeautician[] = [
  {
    id: 'bea-1',
    name: 'Sunita Sharma',
    phone: '+91 98390 12341',
    email: 'sunita.sharma@beautynest.in',
    area: 'Sigra',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&q=80',
    skills: ['Korean Glass Skin', 'O3+ Whitening', 'Rica Waxing'],
    experienceYears: 8,
    rating: 4.95,
    totalJobs: 1240,
    isOnline: true,
    kycStatus: 'APPROVED',
    earningsToday: 4850,
    aadhaarNumber: 'XXXX-XXXX-4512',
    upiId: 'sunita@upi',
  },
  {
    id: 'bea-2',
    name: 'Pooja Maurya',
    phone: '+91 98390 12342',
    email: 'pooja.maurya@beautynest.in',
    area: 'Lanka (BHU)',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&q=80',
    skills: ['Bridal HD Makeup', 'Hair Spa', 'Saree Draping'],
    experienceYears: 6,
    rating: 4.92,
    totalJobs: 890,
    isOnline: true,
    kycStatus: 'APPROVED',
    earningsToday: 5400,
    aadhaarNumber: 'XXXX-XXXX-8821',
    upiId: 'pooja.m@okhdfcbank',
  },
  {
    id: 'bea-3',
    name: 'Anjali Gupta',
    phone: '+91 98390 12343',
    email: 'anjali.gupta@beautynest.in',
    area: 'Assi Ghat',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&q=80',
    skills: ['Aromatherapy Spa', 'Body Polishing', 'Deluxe Mani-Pedi'],
    experienceYears: 5,
    rating: 4.88,
    totalJobs: 640,
    isOnline: true,
    kycStatus: 'APPROVED',
    earningsToday: 3200,
    aadhaarNumber: 'XXXX-XXXX-6729',
    upiId: 'anjali@paytm',
  },
  {
    id: 'bea-4',
    name: 'Neha Pandey',
    phone: '+91 98390 12344',
    email: 'neha.pandey@beautynest.in',
    area: 'Godowlia',
    avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&q=80',
    skills: ['Diamond Facial', 'Sara Oxy D-Tan', 'Rica Brazilian Wax'],
    experienceYears: 7,
    rating: 4.96,
    totalJobs: 1120,
    isOnline: true,
    kycStatus: 'APPROVED',
    earningsToday: 6100,
    aadhaarNumber: 'XXXX-XXXX-9918',
    upiId: 'neha.p@ybl',
  },
  {
    id: 'bea-5',
    name: 'Rekha Vishwakarma',
    phone: '+91 98390 12345',
    email: 'rekha.v@beautynest.in',
    area: 'Bhelupur',
    avatarUrl: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=400&q=80',
    skills: ['Keratin Treatment', 'Hair Botox', 'Global Highlights'],
    experienceYears: 9,
    rating: 4.98,
    totalJobs: 1450,
    isOnline: true,
    kycStatus: 'APPROVED',
    earningsToday: 7800,
    aadhaarNumber: 'XXXX-XXXX-3342',
    upiId: 'rekha@axisbank',
  },
  {
    id: 'bea-6',
    name: 'Priya Singh',
    phone: '+91 98390 12346',
    email: 'priya.singh@beautynest.in',
    area: 'Varanasi Cantt',
    avatarUrl: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=400&q=80',
    skills: ['Roll-on Waxing', 'Sara Clean-up', 'Threading Combo'],
    experienceYears: 4,
    rating: 4.85,
    totalJobs: 480,
    isOnline: false,
    kycStatus: 'APPROVED',
    earningsToday: 1800,
    aadhaarNumber: 'XXXX-XXXX-1290',
    upiId: 'priya.s@sbi',
  },
  {
    id: 'bea-7',
    name: 'Archana Yadav',
    phone: '+91 98390 12347',
    email: 'archana.yadav@beautynest.in',
    area: 'Shivpur',
    avatarUrl: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=400&q=80',
    skills: ['Lotus Radiant Gold', 'Bleach & D-Tan', 'Swedish Spa'],
    experienceYears: 6,
    rating: 4.89,
    totalJobs: 720,
    isOnline: true,
    kycStatus: 'APPROVED',
    earningsToday: 2950,
    aadhaarNumber: 'XXXX-XXXX-5519',
    upiId: 'archana@icici',
  },
  {
    id: 'bea-8',
    name: 'Kavita Mishra',
    phone: '+91 98390 12348',
    email: 'kavita.mishra@beautynest.in',
    area: 'Mahmoorganj',
    avatarUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=400&q=80',
    skills: ['Royal Bridal Makeup', 'Sangeet Glam', 'Airbrush Look'],
    experienceYears: 8,
    rating: 4.94,
    totalJobs: 1050,
    isOnline: true,
    kycStatus: 'APPROVED',
    earningsToday: 6900,
    aadhaarNumber: 'XXXX-XXXX-7721',
    upiId: 'kavita.m@upi',
  },
  {
    id: 'bea-9',
    name: 'Shalini Verma',
    phone: '+91 98390 12349',
    email: 'shalini.verma@beautynest.in',
    area: 'Orderly Bazar',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&q=80',
    skills: ['L’Oreal Hair Spa', 'O3+ Whitening', 'Rica Waxing'],
    experienceYears: 5,
    rating: 4.86,
    totalJobs: 530,
    isOnline: true,
    kycStatus: 'APPROVED',
    earningsToday: 3400,
    aadhaarNumber: 'XXXX-XXXX-9902',
    upiId: 'shalini@kotak',
  },
  {
    id: 'bea-10',
    name: 'Suman Srivastava',
    phone: '+91 98390 12350',
    email: 'suman.s@beautynest.in',
    area: 'Pandeypur',
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&q=80',
    skills: ['Crystal Spa Pedicure', 'Gel Nails', 'Cheryl’s GloVite'],
    experienceYears: 7,
    rating: 4.91,
    totalJobs: 910,
    isOnline: true,
    kycStatus: 'APPROVED',
    earningsToday: 4100,
    aadhaarNumber: 'XXXX-XXXX-8834',
    upiId: 'suman@pnb',
  },
  {
    id: 'bea-11',
    name: 'Ritu Tripathi',
    phone: '+91 98390 12351',
    email: 'ritu.t@beautynest.in',
    area: 'Sarnath',
    avatarUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=400&q=80',
    skills: ['Deep Tissue Massage', 'Aromatherapy', 'Body Polishing'],
    experienceYears: 6,
    rating: 4.9,
    totalJobs: 770,
    isOnline: false,
    kycStatus: 'APPROVED',
    earningsToday: 0,
    aadhaarNumber: 'XXXX-XXXX-4412',
    upiId: 'ritu@barodampay',
  },
  {
    id: 'bea-12',
    name: 'Poonam Tiwari',
    phone: '+91 98390 12352',
    email: 'poonam.tiwari@beautynest.in',
    area: 'Durgakund',
    avatarUrl: 'https://images.unsplash.com/photo-1548142813-c348350df52b?w=400&q=80',
    skills: ['O3+ Bridal Glow', 'Kashi Bridal Master', 'Hair Botox'],
    experienceYears: 10,
    rating: 4.99,
    totalJobs: 1620,
    isOnline: true,
    kycStatus: 'APPROVED',
    earningsToday: 8200,
    aadhaarNumber: 'XXXX-XXXX-1178',
    upiId: 'poonam@okhdfcbank',
  },
  {
    id: 'bea-13',
    name: 'Mamta Jaiswal',
    phone: '+91 98390 12353',
    email: 'mamta.j@beautynest.in',
    area: 'Luxa',
    avatarUrl: 'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=400&q=80',
    skills: ['Honey Waxing', 'Sara D-Tan', 'Papaya Clean Up'],
    experienceYears: 4,
    rating: 4.82,
    totalJobs: 410,
    isOnline: true,
    kycStatus: 'APPROVED',
    earningsToday: 2100,
    aadhaarNumber: 'XXXX-XXXX-5589',
    upiId: 'mamta@upi',
  },
  {
    id: 'bea-14',
    name: 'Vandana Patel',
    phone: '+91 98390 12354',
    email: 'vandana.patel@beautynest.in',
    area: 'Rathyatra',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&q=80',
    skills: ['Korean Glass Skin', 'Hydra Facial', 'Rica Brazilian'],
    experienceYears: 7,
    rating: 4.93,
    totalJobs: 990,
    isOnline: true,
    kycStatus: 'APPROVED',
    earningsToday: 5100,
    aadhaarNumber: 'XXXX-XXXX-6623',
    upiId: 'vandana@axis',
  },
  {
    id: 'bea-15',
    name: 'Babita Dubey',
    phone: '+91 98390 12355',
    email: 'babita.dubey@beautynest.in',
    area: 'Maldahiya',
    avatarUrl: 'https://images.unsplash.com/photo-1502685104226-ee32379fefbe?w=400&q=80',
    skills: ['L’Oreal Majirel Color', 'Hair Spa', 'Cut & Blowdry'],
    experienceYears: 5,
    rating: 4.87,
    totalJobs: 620,
    isOnline: true,
    kycStatus: 'APPROVED',
    earningsToday: 3100,
    aadhaarNumber: 'XXXX-XXXX-3312',
    upiId: 'babita@ybl',
  },
  {
    id: 'bea-16',
    name: 'Preeti Rawat',
    phone: '+91 98390 12356',
    email: 'preeti.rawat@beautynest.in',
    area: 'Chowk',
    avatarUrl: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=400&q=80',
    skills: ['Sara Oxy D-Tan', 'Diamond Facial', 'Body Massage'],
    experienceYears: 6,
    rating: 4.89,
    totalJobs: 810,
    isOnline: true,
    kycStatus: 'PENDING',
    earningsToday: 0,
    aadhaarNumber: 'XXXX-XXXX-7788',
    upiId: 'preeti@sbi',
  },
  {
    id: 'bea-17',
    name: 'Deepa Sen',
    phone: '+91 98390 12357',
    email: 'deepa.sen@beautynest.in',
    area: 'Nadesar',
    avatarUrl: 'https://images.unsplash.com/photo-1520813792240-56fc4a3765a7?w=400&q=80',
    skills: ['Deluxe Mani-Pedi', 'Crystal Pedicure', 'Threading'],
    experienceYears: 4,
    rating: 4.83,
    totalJobs: 460,
    isOnline: true,
    kycStatus: 'PENDING',
    earningsToday: 0,
    aadhaarNumber: 'XXXX-XXXX-9923',
    upiId: 'deepa@paytm',
  },
  {
    id: 'bea-18',
    name: 'Meena Chaurasia',
    phone: '+91 98390 12358',
    email: 'meena.c@beautynest.in',
    area: 'Paharia',
    avatarUrl: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=400&q=80',
    skills: ['Cheryl’s Cosmeceuticals', 'Rica Waxing', 'Hair Spa'],
    experienceYears: 8,
    rating: 4.95,
    totalJobs: 1180,
    isOnline: true,
    kycStatus: 'APPROVED',
    earningsToday: 5900,
    aadhaarNumber: 'XXXX-XXXX-1145',
    upiId: 'meena@icici',
  },
  {
    id: 'bea-19',
    name: 'Swati Agrawal',
    phone: '+91 98390 12359',
    email: 'swati.agrawal@beautynest.in',
    area: 'Ramnagar',
    avatarUrl: 'https://images.unsplash.com/photo-1546961329-78bef0414d7c?w=400&q=80',
    skills: ['Engagement Makeup', 'Saree Draping', 'Hydra Facial'],
    experienceYears: 5,
    rating: 4.88,
    totalJobs: 670,
    isOnline: false,
    kycStatus: 'APPROVED',
    earningsToday: 0,
    aadhaarNumber: 'XXXX-XXXX-6671',
    upiId: 'swati@okhdfcbank',
  },
  {
    id: 'bea-20',
    name: 'Garima Pathak',
    phone: '+91 98390 12360',
    email: 'garima.pathak@beautynest.in',
    area: 'Dashashwamedh',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&q=80',
    skills: ['Full Body Sea Salt Polishing', 'Swedish Spa', 'O3+ Facial'],
    experienceYears: 7,
    rating: 4.92,
    totalJobs: 940,
    isOnline: true,
    kycStatus: 'PENDING',
    earningsToday: 0,
    aadhaarNumber: 'XXXX-XXXX-8812',
    upiId: 'garima@upi',
  },
];

export const CUSTOMERS_LIST: AdminCustomer[] = [
  {
    id: 'cus-1',
    name: 'Priya Verma',
    phone: '+91 98390 55110',
    area: 'Sigra, Varanasi',
    totalBookings: 8,
    totalSpent: 8420,
    lastBooking: 'Today, 11:30 AM',
  },
  {
    id: 'cus-2',
    name: 'Dr. Shalini Kapoor',
    phone: '+91 98390 55220',
    area: 'Lanka (BHU), Varanasi',
    totalBookings: 14,
    totalSpent: 16850,
    lastBooking: 'Yesterday',
  },
  {
    id: 'cus-3',
    name: 'Meenakshi Rastogi',
    phone: '+91 98390 55330',
    area: 'Bhelupur, Varanasi',
    totalBookings: 5,
    totalSpent: 5120,
    lastBooking: '2 days ago',
  },
  {
    id: 'cus-4',
    name: 'Shweta Upadhyay',
    phone: '+91 98390 55440',
    area: 'Mahmoorganj, Varanasi',
    totalBookings: 9,
    totalSpent: 11400,
    lastBooking: '3 days ago',
  },
];
